#!/bin/sh

ARCHIVER_CMD=zip
ARCHIVE_EXT=.zip

INPUT_DIRECTORY=bin
INPUT_BINARY_NAME=ble
INPUT_BINARY_DEBUG_SUFFIX=_Debug
INPUT_BINARY_RELEASE_SUFFIX=_Release
INPUT_DEBUG_BINARY_NAME=${INPUT_BINARY_NAME}${INPUT_BINARY_DEBUG_SUFFIX}.exe
INPUT_RELEASE_BINARY_NAME=${INPUT_BINARY_NAME}${INPUT_BINARY_RELEASE_SUFFIX}.exe
OUTPUT_NAME=sim
OUTPUT_DEBUG_SUFFIX=_debug
OUTPUT_RELEASE_SUFFIX=_release
OUTPUT_DEBUG_BINARY_NAME=${OUTPUT_NAME}${OUTPUT_DEBUG_SUFFIX}.exe
OUTPUT_RELEASE_BINARY_NAME=${OUTPUT_NAME}${OUTPUT_RELEASE_SUFFIX}.exe

DEBUG_FILES="${INPUT_DIRECTORY}/${OUTPUT_DEBUG_BINARY_NAME} ${INPUT_DIRECTORY}/msvcp100d.dll ${INPUT_DIRECTORY}/msvcr100d.dll"
RELEASE_FILES="${INPUT_DIRECTORY}/${OUTPUT_RELEASE_BINARY_NAME} ${INPUT_DIRECTORY}/Assimp32.dll ${INPUT_DIRECTORY}/msvcp100.dll ${INPUT_DIRECTORY}/msvcr100.dll"
SHARED_FILES="${INPUT_DIRECTORY}/glew32.dll ${INPUT_DIRECTORY}/Assimp32.dll ${INPUT_DIRECTORY}/data/*/*"

DEBUG_ARCHIVE=${OUTPUT_NAME}${OUTPUT_DEBUG_SUFFIX}${ARCHIVE_EXT}
RELEASE_ARCHIVE=${OUTPUT_NAME}${OUTPUT_RELEASE_SUFFIX}${ARCHIVE_EXT}
ALL_ARCHIVE=${OUTPUT_NAME}${ARCHIVE_EXT}

# remove exising archives, if present
rm -f ${DEBUG_ARCHIVE} ${RELEASE_ARCHIVE} ${ALL_ARCHIVE}

# remove old binaries
rm -f ${INPUT_DIRECTORY}/${OUTPUT_DEBUG_BINARY_NAME} ${INPUT_DIRECTORY}/${OUTPUT_RELEASE_BINARY_NAME}

# copy new binaries
cp ${INPUT_DEBUG_BINARY_NAME} ${INPUT_DIRECTORY}/${OUTPUT_DEBUG_BINARY_NAME}
cp ${INPUT_RELEASE_BINARY_NAME} ${INPUT_DIRECTORY}/${OUTPUT_RELEASE_BINARY_NAME}

${ARCHIVER_CMD} ${DEBUG_ARCHIVE} ${DEBUG_FILES} ${SHARED_FILES}
${ARCHIVER_CMD} ${RELEASE_ARCHIVE} ${RELEASE_FILES} ${SHARED_FILES}
${ARCHIVER_CMD} ${ALL_ARCHIVE} ${DEBUG_FILES} ${RELEASE_FILES} ${SHARED_FILES}

